# application.yaml(根据项目实际情况修改配置)
# DataSource Config
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    # MySQL
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/performancedata?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    # Druid
    druid:
      # 初始化大小，最小，最大
      initial-size: 5
      max-active: 100
      min-idle: 1
      # 配置获取连接等待超时的时间
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存时间
      min-evictable-idle-time-millis: 3000

# Server settings (ServerProperties)
server:
  port: 80
  address: 127.0.0.1
  tomcat:
    accesslog:
      enabled: false
sessionT
# MyBatis-Plus settings
#控制台打印sql
mybatis-plus:
  configuration:
    # 打印日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml
#  global-config:
#    field-strategy字段更新插入策略属性说明：
#    IGNORED(0): "忽略判断", 所有字段都更新和插入
#    NOT_NULL(1): "非 NULL 判断", 只更新和插入非NULL值
#    NOT_EMPTY(2): "非空判断", 只更新和插入非NULL值且非空字符串
#    DEFAULT：默认NOT_NULL
#    field-strategy: 2
  global-config:
    db-config:
      id-type: auto #数据库自增（全局配置）
      logic-delete-field: deleted # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)